#!/bin/sh

set -e
set -x

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends \
  mono-runtime \
  mono-mcs \
  binfmt-support \
  libmono-system-web4.0-cil \
  libmono-microsoft-csharp4.0-cil
apt-get clean
adduser --system --home /srv/opensim --uid 900 --group --quiet opensim
