#!/bin/sh

set -e

if [ -x /srv/opensim/run_opensim ]; then
    cd /srv/opensim
    exec /srv/opensim/run_opensim
elif [ -e /srv/opensim/bin/OpenSim.exe ]; then
    cd /srv/opensim/bin
    exec mono OpenSim.exe
else
    echo "The opensim user is:"
    echo "    $(id opensim)"
    echo
    echo "Please bind mount to /srv/opensim.  Then:"
    echo "  - Have an executable named run_opensim in /srv/opensim/, or"
    echo "  - Have OpenSim.exe in /srv/opensim/bin/"
    exit 1
fi
